name: Coveralls
on: [ push, pull_request ]

jobs:
  wear:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2.4.2
      - name: Node.js environment
        uses: actions/setup-node@v3.3.0
      - run: npm install
      - name: Test
        run: npm run test || exit 0
      - name: Coveralls action
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
